### PR TITLE
move metadata texts from fdroiddata to here

### PR DESCRIPTION
**Pull request by eighthave**
The upstream repo is the best place to maintain these files, then you can also manage how these files are translated, etc.  The fdroiddata maintainers are too overloaded to maintain these kinds of things.

### CODE REVIEW

**Comment by hyst329** [comment]
Thanks! Hope to review and merge this at the weekend.

**Comment by eighthave** [comment]
any word on this?  the CI test failure is something to do with running _openssl_, which this pull request didn't touch.

**Comment by hyst329** [comment]
Oh, I've completely forgotten about it. Merged.

**Comment by eighthave** [comment]
let me know when you've tagged a new release with this, and I'll remove
the files from _fdroiddata_ so that the files from your repo are used.

**Pull request merged**
